--- #YAML:1.0
name:                Linux-Smaps
version:             0.06
abstract:            a Perl interface to /proc/PID/smaps
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Member:                 1.3
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Torsten Foertsch <torsten.foertsch@gmx.net>
