# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Linux-Smaps
version:      0.04
version_from: lib/Linux/Smaps.pm
installdirs:  site
requires:
    Class::Member:                 1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
